//! The application icon.
//!
//! One source of truth: `assets/logo.png` is the logo; `assets/icon_256.png`
//! (the same art, squared to 256×256) is embedded here with `include_bytes!`
//! and decoded at start-up into the RGBA buffer eframe wants for the window
//! icon. The Windows executable additionally carries `assets/logo.ico` via
//! `build.rs`/`winresource`, which Explorer and the taskbar use — the window
//! manager icon and the exe icon come from the same art, generated by the
//! same ImageMagick step.

/// Decode the embedded 256×256 icon into eframe's format.
///
/// Returns `None` only if the embedded PNG fails to decode — which would be a
/// build-time asset corruption, not a user condition. Callers treat that as
/// "no icon" rather than failing the launch: a coaching session must never
/// refuse to start over decoration.
pub fn window_icon() -> Option<eframe::egui::IconData> {
    decode_png_icon(include_bytes!("../../assets/icon_256.png"))
}

/// Decode an RGBA PNG buffer into eframe's icon format.
fn decode_png_icon(bytes: &[u8]) -> Option<eframe::egui::IconData> {
    let decoder = png::Decoder::new(std::io::Cursor::new(bytes));
    let mut reader = decoder.read_info().ok()?;
    let mut rgba = vec![0u8; reader.output_buffer_size()];
    let info = reader.next_frame(&mut rgba).ok()?;
    if info.color_type != png::ColorType::Rgba {
        return None; // the asset pipeline must emit RGBA, not a paletted PNG
    }
    Some(eframe::egui::IconData {
        rgba,
        width: info.width,
        height: info.height,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_embedded_icon_decodes_to_a_square_rgba_image() {
        let icon = window_icon().expect("the embedded icon_256.png must decode");
        assert_eq!(icon.width, 256);
        assert_eq!(icon.height, 256);
        assert_eq!(icon.rgba.len(), 256 * 256 * 4);
        // The buffer really has transparency somewhere (the art is letterboxed
        // on a transparent square) and opaque pixels somewhere (the art
        // itself), so the decoder's RGBA claim is not vacuous.
        assert!(icon.rgba.iter().skip(3).step_by(4).any(|a| *a < 255));
        assert!(icon.rgba.iter().skip(3).step_by(4).any(|a| *a == 255));
    }

    #[test]
    fn a_non_rgba_png_is_rejected_rather_than_misread() {
        // A 1×1 grayscale PNG: a format the loader does not promise to read.
        let grey = [
            0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, // PNG signature
            0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52, // IHDR
            0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, // 1×1
            0x08, 0x00, 0x00, 0x00, 0x00, 0x37, 0x6E, 0xF9, // 8-bit greyscale
            0x24, // CRC
            0x00, 0x00, 0x00, 0x0A, 0x49, 0x44, 0x41, 0x54, // IDAT
            0x78, 0x9C, 0x63, 0x00, 0x01, 0x00, 0x00, 0x05, 0x00, 0x01, //
            0x0D, 0x0A, 0x2D, 0xB4, // CRC
            0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, 0x44, // IEND
            0xAE, 0x42, 0x60, 0x82, // CRC
        ];
        assert!(decode_png_icon(&grey).is_none());
    }

    #[test]
    fn garbage_bytes_are_rejected_without_panicking() {
        assert!(decode_png_icon(b"not a png at all").is_none());
        assert!(decode_png_icon(&[]).is_none());
    }
}
